[pytest]
testpaths = tests
pythonpath = src
markers =
    integration: marks tests as integration (deselect with '-m "not integration"')
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince212
    ignore::DeprecationWarning:spacy.*
    ignore::DeprecationWarning:weasel.*
    ignore::DeprecationWarning:pydub.*
    ignore::UserWarning:torch.*
    ignore::FutureWarning:torch.*
